version: '2.2'
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    volumes:
      - /etc/rancher-data:/var/lib/rancher
    ports:
      - 80:80
      - 443:443
    privileged: true

volumes:
  rancher-data:
    driver: local
