---
- name: Generate and Execute Master Join Token
  hosts: master[0]
  gather_facts: false
  become: true

  tasks:
    - name: Generate certificates
      command: kubeadm init phase upload-certs --upload-certs
      register: certs_output

    - name: Generate join token
      command: kubeadm token create --certificate-key "{{ certs_output.stdout }}" --print-join-command
      register: join_command_output
  
    - name: Set fact for Master Join Token
      set_fact:
        join_command_output: "{{ join_command_output.stdout_lines[0] }}"

- name: Execute Master Join Command on Masternodes
  hosts: master[1:]
  become: true
  become_user: root
  tasks:
    - name: Join Master Node to Cluster
      command: "{{ hostvars[groups['master'][0]]['join_command_output'] }}"
