- name: Generate token on master[0]
  hosts: master[0]
  tasks:
    - name: Generate Master Join Token  
      command: kubeadm token create --print-join-command
      register: master_join_token   

- name: Execute token on other master nodes     
  hosts: master
  tasks:     
    - name: Set Master Join Command as Fact
      set_fact:
        master_join_command: "{{ hostvars['master[0]'].master_join_token.stdout_lines[0] }}"

    - name: Execute Master Join Command
      command: "{{ master_join_command }}"
      become_user: root