- name: Generate token on master[0]
  hosts: master[0]
  tasks:
    - name: Generate Master Join Token  
      command: kubeadm token create --print-join-command
      register: master_join_token   

    - name: Set Master Join Token as Fact
      set_fact:
        master_join_command: "{{ master_join_token.stdout_lines[0] }}"

    - name: Print Master Join Token
      debug:
        var: master_join_command

- name: Execute token on other master nodes     
  hosts: master[1:]
  tasks:     
    - name: Execute Master Join Command
      command: "{{ hostvars['master[0]']['master_join_command'] }}"
      become_user: root