- name: Generate and Execute Worker Join Token
  hosts: master[0]
  gather_facts: false
  become: true

  tasks:
    - name: Generate Worker Join Token
      command: kubeadm token create --print-join-command
      register: worker_join_token

    - name: Retrieve Worker Join Token
      set_fact:
        worker_join_command: "{{ worker_join_token.stdout_lines[0] }}"

    - name: Execute Worker Join Command on Workernodes
      command: "{{ worker_join_command }}"
      become_user: root
      when: "'worker' in group_names"