- name: Install and configure Keepalived and HAProxy
  hosts: loadbalancer
  roles:
    #- haproxy_keepalived
    #- configure_keepalived
    - install_haproxy
    - configure_haproxy

- name: Install Kubernetes
  hosts: master:worker
  roles:
    - install_kubernetes

- name: Initialize Kubernetes on first master
  hosts: master[0]
  roles:
    - init_kubernetes

- name: Join the worker nodes
  hosts: worker
  roles:
    - join_worker

- name: Join the master nodes
  hosts: "{{ groups['master'] | skip(0) }}"
  roles:
    - join_master

- name: Install Rancher
  hosts: master
  roles:
    - rancher_setup