- name: Install Keepalived & Haproxy
  import_playbook: playbooks/haproxy_keepalived.yml

- name: Configure Keepalived
  import_playbook: playbooks/conf_keeplived.yml

- name: Configure HAproxy
  import_playbook: playbooks/conf_haproxy.yml

- name: Install Kubernetes
  import_playbook: playbooks/install_kubernetes.yml

- name: Kubernetes init 
  import_playbook: playbooks/init_kubernetes.yml

- name: Join masters
  import_playbook: playbooks/join_master.yml

- name: Join workers
  import_playbook: playbooks/join_worker.yml

- name: Install rancher
  import_playbook: playbooks/rancher_setup.yml
