---
- name: Install Kubernetes
  hosts: master:worker
  become: true
  
  tasks:
  - name: Disable swap
    command: swapoff -a
  - name: Remove swap entry from /etc/fstab
    lineinfile:
      path: /etc/fstab
      state: absent
      regexp: '^/swap.*'
  - name: Disable Firewall
    service:
      name: ufw
      state: stopped
      enabled: no
  - name: Enable and load kernel modules
    copy:
      content: |
        overlay
        br_netfilter
      dest: /etc/modules-load.d/containerd.conf
  - name: Load kernel modules
    command: modprobe {{ item }}
    with_items:
      - overlay
      - br_netfilter
  - name: Add kernel settings
    copy:
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
      dest: /etc/sysctl.d/kubernetes.conf
  - name: Reload kernel settings
    command: sysctl --system
  - name: Install containerd
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: present
    with_items:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - containerd.io
  - name: Configure containerd
    copy:
      content: |
        [plugins."io.containerd.grpc.v1.cri".containerd]
          systemd_cgroup = true
      dest: /etc/containerd/config.toml
  - name: Restart containerd
    service:
      name: containerd
      state: restarted
  - name: Configure cgroup v2
    lineinfile:
      path: /etc/default/grub
      state: present
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="cgroup_no_v1=net_prio,net_cls"'
    notify: Update GRUB
  - name: Install Kubernetes packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - kubelet
      - kubeadm
      - kubectl
  - name: Hold Kubernetes packages
    apt:
      name: "{{ item }}"
      state: held
    with_items:
      - kubelet
      - kubeadm
      - kubectl

  handlers:
  - name: Update GRUB
    command: update-grub